language: java
jdk:
- oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  sauce_connect:
    username: "SantiMA10"
    access_key:
      secure: "htJQ0nx/qJZIs+8D2YS4iPug8XqvZadpaIc1O4JxStednHxIN97ol1aMdb035RgG5CGLUIeHKMpDgHkQ5XZvYMiuwxyqRqKZLNnICmVm1a5rCPW1mLPM5zAGsBi9zi8KPeLzcMCYOLKCiujy4QRVlcEHD2xsgB/FpSYfRAi25F/iB7BT1sjqdihk391vSSQ1e0CcBoii5XuBRxcAhQhiwupzrQRKET0wARPsEQSoTRuRG0jZL47DqFbmYvcG5kmByiKZnMg+U76CBGJnxZsTPpLqNhtNDODGRUqx6pWLRoPGlVyDsggfpbiReDCn9DtrwkHXQQBzkUj6LokcEW+480UtuWoKtoQdLO3KfkzDoPGtOdu6wp7/aa2jVekwVcnoDGMBj4OnbEKeF1ciEU0WaOztaa7kI3LHfpdPWRZsoUIy+Y9bzYgVZ7GyR4/YWPwKM85ojaKzIdPP/SkdySjAiG8DCR6NKPMbSQFBD7/WFlQEYD0YVvbUj5w0iz5Sl/tiAJLasKnk+Wdm98RC7baBE9IXAdS0vWakcOHWtHCZPzsgjl8bA72UbynmbiKkDEAJ1gCA8tLjga63oiUuEflTgJuQYHwN2EdwMZvNS6cFbTPWaIzOPJf1orUZQ6SNv2EZOf8gvEKrhoozn4r0cQi2/qoCt7VgFee8Inzc6xn7s0Y="
services:
  - mysql
before_script:
  - mysql -e 'create database censuses_1b;'
